spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManagerDB
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    showSql: true
  sql:
    init.mode: always
