CREATE TABLE project
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR(256) NOT NULL,
    description   TEXT         NOT NULL,
    creation_date DATE         NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE task
(
    id            INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR(256) NOT NULL,
    description   TEXT         NOT NULL,
    creation_date DATE         NOT NULL DEFAULT CURRENT_DATE,
    project_id    INT REFERENCES project (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE employee
(
    id     INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(256)
);

CREATE TABLE employee_task
(
    task_id     INT REFERENCES task (id) ON DELETE CASCADE ON UPDATE CASCADE,
    employee_id INT REFERENCES employee (id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (task_id, employee_id)
);